//! Platform-independent connection lifecycle.
//!
//! This crate does not dial VPNs, verify networks or forward traffic. Adapters
//! must obtain real probe results, enforce egress restrictions and honor the
//! forwarding gate. A model test is not a VPN compatibility result.

use std::sync::atomic::{AtomicU64, Ordering};

static ATTEMPTS: AtomicU64 = AtomicU64::new(0);

// IDs are unique across sessions in one controller process. They are ephemeral
// and must not be restored after a controller restart without revalidation.
fn allocate_attempt(counter: &AtomicU64) -> Result<u64, Error> {
    counter
        .fetch_update(Ordering::Relaxed, Ordering::Relaxed, |value| {
            value.checked_add(1)
        })
        .map(|previous| previous + 1)
        .map_err(|_| Error::AttemptCounterExhausted)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AttemptId(u64);

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    Idle,
    Starting,
    AwaitingLogin,
    Probing,
    Ready,
    Failed,
}

/// Inputs supplied by trusted adapters, not evidence generated by this crate.
#[derive(Debug, Clone, Copy, Default)]
pub struct Readiness {
    pub authenticated: bool,
    pub management_channel: bool,
    pub intranet_probe: bool,
    pub egress_guard: bool,
}

impl Readiness {
    fn complete(self) -> bool {
        self.authenticated && self.management_channel && self.intranet_probe && self.egress_guard
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    InvalidState,
    StaleAttempt,
    IncompleteReadiness,
    AttemptCounterExhausted,
}

#[derive(Debug)]
pub struct Session {
    state: State,
    generation: u64,
}

impl Default for Session {
    fn default() -> Self {
        Self {
            state: State::Idle,
            generation: 0,
        }
    }
}

impl Session {
    pub fn state(&self) -> State {
        self.state
    }

    pub fn may_forward(&self) -> bool {
        self.state == State::Ready
    }

    pub fn begin(&mut self) -> Result<AttemptId, Error> {
        if !matches!(self.state, State::Idle | State::Failed) {
            return Err(Error::InvalidState);
        }
        let generation = allocate_attempt(&ATTEMPTS)?;
        self.generation = generation;
        self.state = State::Starting;
        Ok(AttemptId(generation))
    }

    pub fn environment_started(&mut self, attempt: AttemptId) -> Result<(), Error> {
        self.transition(attempt, State::Starting, State::AwaitingLogin)
    }

    pub fn login_finished(&mut self, attempt: AttemptId) -> Result<(), Error> {
        self.transition(attempt, State::AwaitingLogin, State::Probing)
    }

    pub fn finish_probe(&mut self, attempt: AttemptId, readiness: Readiness) -> Result<(), Error> {
        self.check(attempt, State::Probing)?;
        if !readiness.complete() {
            return Err(Error::IncompleteReadiness);
        }
        self.state = State::Ready;
        Ok(())
    }

    /// Close the gate immediately; the adapter still must tear down active flows.
    pub fn disconnect(&mut self) {
        self.state = State::Idle;
    }

    pub fn failed(&mut self, attempt: AttemptId) -> Result<(), Error> {
        if attempt.0 != self.generation {
            return Err(Error::StaleAttempt);
        }
        if matches!(self.state, State::Idle | State::Failed) {
            return Err(Error::InvalidState);
        }
        self.state = State::Failed;
        Ok(())
    }

    fn check(&self, attempt: AttemptId, expected: State) -> Result<(), Error> {
        if attempt.0 != self.generation {
            return Err(Error::StaleAttempt);
        }
        if self.state != expected {
            return Err(Error::InvalidState);
        }
        Ok(())
    }

    fn transition(&mut self, attempt: AttemptId, from: State, to: State) -> Result<(), Error> {
        self.check(attempt, from)?;
        self.state = to;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn probing() -> (Session, AttemptId) {
        let mut session = Session::default();
        let attempt = session.begin().unwrap();
        session.environment_started(attempt).unwrap();
        session.login_finished(attempt).unwrap();
        (session, attempt)
    }

    fn complete() -> Readiness {
        Readiness {
            authenticated: true,
            management_channel: true,
            intranet_probe: true,
            egress_guard: true,
        }
    }

    #[test]
    fn forwarding_stays_closed_until_all_checks_finish() {
        let mut session = Session::default();
        assert!(!session.may_forward());
        let attempt = session.begin().unwrap();
        assert!(!session.may_forward());
        session.environment_started(attempt).unwrap();
        assert!(!session.may_forward());
        session.login_finished(attempt).unwrap();
        assert!(!session.may_forward());
        session.finish_probe(attempt, complete()).unwrap();
        assert!(session.may_forward());
    }

    #[test]
    fn every_missing_readiness_check_blocks_forwarding() {
        for flags in 0u8..15 {
            let (mut session, attempt) = probing();
            let readiness = Readiness {
                authenticated: flags & 1 != 0,
                management_channel: flags & 2 != 0,
                intranet_probe: flags & 4 != 0,
                egress_guard: flags & 8 != 0,
            };
            assert_eq!(
                session.finish_probe(attempt, readiness),
                Err(Error::IncompleteReadiness)
            );
            assert!(!session.may_forward());
        }
    }

    #[test]
    fn canceled_attempt_cannot_publish_an_endpoint() {
        let (mut session, attempt) = probing();
        session.disconnect();
        assert_eq!(
            session.finish_probe(attempt, complete()),
            Err(Error::InvalidState)
        );
        assert!(!session.may_forward());
    }

    #[test]
    fn previous_attempt_events_cannot_change_a_new_attempt() {
        let (mut session, old) = probing();
        session.disconnect();
        let current = session.begin().unwrap();
        session.environment_started(current).unwrap();
        session.login_finished(current).unwrap();
        assert_eq!(session.failed(old), Err(Error::StaleAttempt));
        assert_eq!(
            session.finish_probe(old, complete()),
            Err(Error::StaleAttempt)
        );
        assert_eq!(session.state(), State::Probing);
        assert!(!session.may_forward());
    }

    #[test]
    fn failure_closes_a_ready_gate_and_requires_a_new_attempt() {
        let (mut session, old) = probing();
        session.finish_probe(old, complete()).unwrap();
        session.failed(old).unwrap();
        assert!(!session.may_forward());
        assert_eq!(
            session.finish_probe(old, complete()),
            Err(Error::InvalidState)
        );
        assert_ne!(session.begin().unwrap(), old);
    }

    #[test]
    fn out_of_order_and_duplicate_events_are_rejected() {
        let mut session = Session::default();
        let attempt = session.begin().unwrap();
        assert_eq!(session.begin(), Err(Error::InvalidState));
        assert_eq!(session.login_finished(attempt), Err(Error::InvalidState));
        session.environment_started(attempt).unwrap();
        assert_eq!(
            session.environment_started(attempt),
            Err(Error::InvalidState)
        );
    }

    #[test]
    fn disconnecting_one_session_does_not_close_another_gate() {
        let (mut a, a_attempt) = probing();
        let (mut b, b_attempt) = probing();
        a.finish_probe(a_attempt, complete()).unwrap();
        b.finish_probe(b_attempt, complete()).unwrap();
        a.disconnect();
        a.disconnect();
        assert!(!a.may_forward());
        assert!(b.may_forward());
    }

    #[test]
    fn one_session_cannot_accept_another_sessions_probe_result() {
        let (_, a_attempt) = probing();
        let (mut b, b_attempt) = probing();
        assert_ne!(a_attempt, b_attempt);
        assert_eq!(
            b.finish_probe(a_attempt, complete()),
            Err(Error::StaleAttempt)
        );
        assert!(!b.may_forward());
    }

    #[test]
    fn attempt_counter_never_wraps_and_reuses_an_id() {
        let counter = AtomicU64::new(u64::MAX);
        assert_eq!(
            allocate_attempt(&counter),
            Err(Error::AttemptCounterExhausted)
        );
        assert_eq!(counter.load(Ordering::Relaxed), u64::MAX);
    }
}
